### ISSUE TITLE
Option to skip LT-check

### ISSUE THREAD

**Issue by arminWel** [torik42/YaLafi#200]
Hi there,
I'd like to use the script without the LT-check so that I obtain the txt corresponding to the tex-file without any LT-comments. Is there an option for this?

Best Regards

**Comment by matze-dd** [comment]
You can use the basic filter, [see here](https://github.com/matze-dd/YaLafi#command-line-of-pure-filter). Please give me a note if you miss some option from yalafi.shell. For instance, I'm aware that the basic filter does not directly check file inclusions.

**Comment by arminWel** [comment]
Thanks for the quick response. To be honest, I cannot find such an option in the basic filters. If my intent was not clear, here is the use case: I want to copy the raw text corresponding to a tex-file so that I can use another grammar checker on the text. Thus, any LT-check is obstructive. Do I miss the appropriate filter?

**Comment by torik42** [comment]
Notice the difference between modules `yalafi.shell` (with LT check) and `yalafi` (without LT check). The latter is described in [Command line of pure filter](https://github.com/torik42/YaLafi#command-line-of-pure-filter) in the README.

I will close this Issue, but feel free to ask more questions.
