### ISSUE TITLE
Local installation doesn't work after change in build system

### ISSUE THREAD

**Issue by JulianGoeltz** [torik42/YaLafi#232]
Commit 4b708d7 introduced a new build system, and for me this breaks the local builds. I've checked in a new setup with [github actions](https://github.com/JulianGoeltz/MWE_yalafi_20221101/blob/main/.github/workflows/test.yaml) and [indeed the actions show](https://github.com/JulianGoeltz/MWE_yalafi_20221101/actions/runs/3371870034): while `pip install yalafi` still works, the installing from a local, cleaned repository as described in `CONTRIBUTING.md` does not work, while reverting the commit 4b708d7 does work again. 
I don't know this new build system, so unfortunately I can't offer a solution.

It's great to see activity in this project, thanks for that!

**Comment by torik42** [comment]
I just tested again with python 3.9 and pip 22.3 and `pip install .` as well as `pip install --editable .` work well. Which versions of python and pip are you using? I migrated to a more recent (introduced in [PEP 621](https://peps.python.org/pep-0621) in 2020) build configuration. Older versions of pip might be able to install the wheels from PyPI but cannot parse the information to build them. As a side effect, you cannot install with `python setup.py` any more (which wasn’t recommended anyway to my knowledge).

**Comment by torik42** [comment]
Maybe my comment about the wheel is wrong. I haven’t yet published to PyPI. You could test with the version on [test PyPI](https://test.pypi.org/project/yalafi/1.3.1b6) which can be installed with `pip install -i https://test.pypi.org/simple/ yalafi==1.3.1b6`. Does that work on your end?

**Comment by JulianGoeltz** [comment]
Are you sure it is working with just the `pip install .`? Because in the minimal example also with python 3.9 and pip 22.3 (before it was python 3.10 and pip 22.3) it fails to correctly install the package: to be precise, the install step goes through, but afterwards the package cannot be imported.
for the details, see https://github.com/JulianGoeltz/MWE_yalafi_20221101/actions/runs/3397400639/jobs/5649522110#step:4:12

I've [added the testpypi install](https://github.com/JulianGoeltz/MWE_yalafi_20221101/commit/577afb62dc1e5aa9e7a540395579d7cefd596bce) and that [is not working](https://github.com/JulianGoeltz/MWE_yalafi_20221101/actions/runs/3397439807/jobs/5649599245#step:6:14) either


all that happens in that action is that a new container is set up with a specific python version, pip is updated, and then yalafi is installed in different ways, with a subsequent test whether the package can be imported. 
Because python installs sometimes are 'brittle', I thought it best to test it with the github actions, to make sure it's not some residual configuration in my system.
In another project, [I have a workflow](https://github.com/gridspeccer/gridspeccer/blob/master/.github/workflows/run_setup.yaml) that checks this automatically, would you like me to create a PR to add such a workflow here as well?

**Comment by torik42** [comment]
When I create a new conda environment (then `python -c 'import yalafi'` exists with an error), install YaLafi with `python -m pip install .` or `pip install .`, change the directory and try `python -c 'import yalafi'` again, it works. I will try to see where it fails in your action.
