### ISSUE TITLE
Add tests for successful installation

### ISSUE THREAD

**Issue by torik42** [torik42/YaLafi#235]
In #232, @JulianGoeltz suggested adding tests also for successful installation of the package. This should cover
```
python -c 'import yalafi'
python -c 'import yalafi.shell'
pytest tests/test_shell/test_shell.py
```
preferable as a new job in `test.yml` for local installation.
I would very much appreciate a PR, if you find the time @JulianGoeltz.

Additionally, we can add the same to `publish.yml` after test-publishing to PyPI for usual installs.

**Comment by JulianGoeltz** [comment]
Add new job to test.yml for testing installation, responding to #235. This takes care of the first part, testing the local installation.

The shell test is not included (yet), as there is a dependence on the local path. If I `cd` to the package directory to have this path available, it is not a test of the execution anymore IIUC. Any idea for a fix there, or should we just leave that test out?

Regarding the test after pushing to PyPi: my understanding is that the GitHub Actions are executed responding to changes in the repository. This `publish.yml` would have to be executed after a push to PyPi, do you know of a way to trigger this?

**Comment by JulianGoeltz** [comment]
Sure, just started the PR. I have a few questions that I asked there.
