### ISSUE TITLE
yalafi.shell - internal error: error reading JSON output from proofreader

### ISSUE THREAD

**Issue by matze-dd** [torik42/YaLafi#91]
This problem may occur with LanguageTool 5.0 and 5.1, it has been fixed with the daily snapshot from 2020/10/26 ([see here](https://internal1.languagetool.org/snapshots/)). Versions 4.9.1 and below work well.

Apparently, only German texts are affected.

The problem is provoked with an input like
```
auf$\Omega$
```
The plain text sent to LanguageTool is `aufC-C-C`, and LanguageTool replies with an invalid JSON message.

This is due to the [issue here](https://github.com/languagetool-org/languagetool/issues/3757). It has been fixed with the daily snapshot 2020-10-26.

**Comment by torik42** [comment]
Being fixed in LanguageTool two years ago I close this issue.
